import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Lay-out',
  description: 'Generated by me',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} h-full antialiased`} style={{ fontFamily: 'var(--font-rubik)' }}>
      <body className="min-h-full flex flex-col">
        <div>{children}</div>
      </body>
    </html>
  );
}
